{% set name = "cuda-profiler-api" %}
{% set version = "13.4.49" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win64]
{% set target_name = "arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set sha256 = "2af05b9bc91b3fb372c686a8ebd00c8f8099d7084e8c673092d3e4f83db873b2" %}  # [linux64]
{% set sha256 = "25ad94ac231cd588ba0c82afa77e687910439f619b97b311176dcc2f32a99ee0" %}  # [aarch64]
{% set sha256 = "34c38ea6ee834a070ee605799f4488d2a3b05246a36e57ff1d429b11a2a9cc03" %}  # [win64]
{% set sha256 = "b99127f0aad069cd53e5b88c89ca6edbf52b3fb349da11e373778f72ff1ff4c5" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/{{ platform }}/cuda_profiler_api-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-cudart-dev
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  commands:
    - test -f $PREFIX/targets/{{ target_name }}/include/cuda_profiler_api.h  # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/include/cudaProfiler.h       # [linux]
    - if not exist %LIBRARY_INC%\cuda_profiler_api.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\cudaProfiler.h exit 1       # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA Profiler API Headers.
  description: |
    CUDA Profiler API Headers.
  doc_url: https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html#range-replay-define-range

extra:
  recipe-maintainers:
    - conda-forge/cuda
